### ISSUE TITLE
Configuration help...

### ISSUE THREAD

**Issue by bzerangue** [jesse-schein/dwelo-connect#2]
@jesse-schein - Do you have a basic README of how i should setup the configuration file to get this to work with Home Assistant?

Your help is greatly appreciated! Thank you again for pulling together this custom component.

**Comment by bzerangue** [comment]
@jesse-schein - Here is the config setup that I have... 

```yaml
dwelo:
  username: "user@email.com"
  password: "UserPassword"
  uid: 10000
  cid: 100
  gid: 100000
```

but produces a configuration error...

```
Integration error: dwelo - Integration 'dwelo' not found.
```
